name: Display Runner OS Details

on: 
  workflow_dispatch

jobs:
  Runner-info:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Display MacOS Details
      if: runner.os == 'macOS'
      run: |
        echo "OS Details:"
        uname -a
        echo "CPU Details:"
        sysctl -n machdep.cpu
        echo "Memory Details:"
        vm_stat
        echo "Disk Details:"
        df -h

    - name: Display Ubuntu Details
      if: runner.os == 'Linux'
      run: |
        echo "OS Details:"
        uname -a
        echo "CPU Details:"
        lscpu
        echo "Memory Details:"
        free -h
        echo "Disk Details:"
        df -h

    - name: Display Windows Details
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        echo "OS Details:"
        systeminfo
        echo "CPU Details:"
        Get-WmiObject -Query "Select * from Win32_Processor"
        echo "Memory Details:"
        Get-WmiObject -Query "Select * from Win32_PhysicalMemory"
        echo "Disk Details:"
        Get-WmiObject -Query "Select * from Win32_LogicalDisk"
        
    - name: Get env variables and Runner, Worker logs
      if: always()
      run: |
          echo "************************ CHECKING ENV VARIABLES *************************"
          env
          echo "************************ GETTING LOGS ***********************************"
          export BASE_PATH="${RUNNER_WORKSPACE}/../.."
          echo Base directory: $BASE_PATH
          echo Content of base directory:
          ls -als $BASE_PATH
          echo Path of _diag directory: "${BASE_PATH}/_diag"
          echo "************************ CONTENT OF _diag DIRECTORY *********************"
          ls -als "${BASE_PATH}/_diag"
          export RUNNER_LOG=`ls -t ${BASE_PATH}/_diag/Runner* | head -1`
          echo "Newest Runner log file: $RUNNER_LOG"
          echo "************************ CONTENT OF NEWEST RUNNER LOG *******************"
          cat $RUNNER_LOG
          echo "*************************************************************************"
          export WORKER_LOG=`ls -t ${BASE_PATH}/_diag/Worker* | head -1`
          echo "Newest Worker log file: $WORKER_LOG"
          echo "************************ CONTENT OF NEWEST WORKER LOG *******************"
          cat $WORKER_LOG
          echo "*************************************************************************"

